CREATE TABLE ejemplo.Usuario (Id_Usuario INT AUTO_INCREMENT NOT NULL, Nombre VARCHAR(55) NOT NULL, ApellidoP VARCHAR(55) NOT NULL, 
ApellidoM VARCHAR(55) NOT NULL, Telefono VARCHAR(55) NOT NULL, Email VARCHAR(55) NOT NULL, Id_Plantel INT NOT NULL, 
Id_TUsuario INT NOT NULL, Password VARCHAR(55) NOT NULL, ImgUsuario VARCHAR(55) NOT NULL, PRIMARY KEY(Id_Usuario)) ENGINE = InnoDB;